site_name: Shape Mapper
site_url: "https://alexdmiller.github.io/shape-mapper/"

copyright: MIT Licence.

plugins:
  - offline

nav:
  - Home: index.md
  - Get Started: getting-started.md
  - Develop: develop.md
  - Release: release.md
  - Troubleshooting: troubleshooting.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  palette:
    primary: black
    scheme: slate
  features:
    - content.code.copy
    - content.code.select
    - content.code.highlight
    - content.code.annotate
    - navigation.footer
