site_name: Shape Mapper
site_url: "https://shapemapper.dev/"

copyright: MIT Licence.

plugins:
  - offline

nav:
  - Home: index.md
  - 'Getting started': tutorial-getting-started.md
  - Tutorials:
    - 'Mapping a paper-folded object': tutorial-paper-folding.md
    - 'Mapping multiple objects': how-to-multiple-objects.md
    - 'Using multiple projectors': how-to-multiple-projectors.md
  - API reference:  /javadoc/spacefiller/shapemapper/package-summary.html
  - Source code: https://github.com/alexdmiller/shape-mapper

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  palette:
    primary: black
    scheme: slate
  features:
    - content.code.copy
    - content.code.select
    - content.code.highlight
    - content.code.annotate
    - navigation.footer
