site_name: Shape Mapper
site_url: "https://alexdmiller.github.io/shape-mapper/"

copyright: MIT Licence.

plugins:
  - offline
  - mkdocstrings:
      handlers:
        java:
          setup_commands:
            - import java.util.*
          selection:
            docstring_style: javadoc

nav:
  - Home: index.md
  - Tutorials:
    - 'Getting started': tutorial-getting-started.md
    - 'Map a paper-folded object': tutorial-paper-folding.md
  - How-tos:
    - 'Map multiple objects': how-to-multiple-objects.md
    - 'Use multiple projectors': how-to-multiple-projectors.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  palette:
    primary: black
    scheme: slate
  features:
    - content.code.copy
    - content.code.select
    - content.code.highlight
    - content.code.annotate
    - navigation.footer
