site_name: Shape Mapper
site_url: "https://alexdmiller.github.io/shape-mapper/"

copyright: MIT Licence.

plugins:
  - offline

nav:
  - Home: index.md
  - Get Started: getting-started.md
  - Develop: develop.md
  - Release: release.md
  - Troubleshooting: troubleshooting.md

theme:
  name: material
  scheme: slate
  palette:
    primary: black
  features:
    - content.code.copy
    - content.code.select
    - content.code.highlight
    - content.code.annotate
    - navigation.footer
